// Generated from libavcodec/vulkan/dirac/dirac_fidelity_vert.comp
const char *ff_source_dirac_fidelity_vert_comp =
"layout(push_constant, std430) uniform pushConstants {\n"
"    ivec2 plane_sizes[3];\n"
"    int plane_offs[3];\n"
"    int plane_strides[3];\n"
"    int dw[3];\n"
"    int wavelet_depth;\n"
"};\n"
"\n"
"int getIdx(int plane, int x, int y) {\n"
"  return plane_offs[plane] + plane_strides[plane] * y + x;\n"
"}\n"
"\n"
"int32_t fidelity_low(int32_t v0, int32_t v1, int32_t v2, int32_t v3,\n"
"                        int32_t v4, int32_t v5, int32_t v6, int32_t v7) {\n"
"    return  (-2 * v0 + 10 * v1 - 25 * v2 + 81 * v3 + 81 * v4 - 25 * v5 + 10 * v6 - 2 * v7 + 128) >> 8;\n"
"}\n"
"\n"
"int32_t fidelity_high(int32_t v0, int32_t v1, int32_t v2, int32_t v3,\n"
"                        int32_t v4, int32_t v5, int32_t v6, int32_t v7) {\n"
"    return  (-8 * v0 + 21 * v1 - 46 * v2 + 161 * v3 + 161 * v4 - 46 * v5 + 21 * v6 - 8 * v7 + 128) >> 8;\n"
"}\n"
"\n"
"int32_t fidelity_low_y(int plane, int x, int y) {\n"
"    const int h = plane_sizes[plane].y;\n"
"\n"
"    const int32_t v1 = inBuf[getIdx(plane, x, y + 1)];\n"
"\n"
"    const int y_6 = ((y - 6) > 0) ? (y - 6) : 0;\n"
"    const int32_t v_6 = inBuf[getIdx(plane, x, y_6)];\n"
"\n"
"    const int y_4 = ((y - 4) > 0) ? (y - 4) : 0;\n"
"    const int32_t v_4 = inBuf[getIdx(plane, x, y_4)];\n"
"\n"
"    const int y_2 = ((y - 2) > 0) ? (y - 2) : 0;\n"
"    const int32_t v_2 = inBuf[getIdx(plane, x, y_2)];\n"
"\n"
"    const int32_t v0 = inBuf[getIdx(plane, x, y)];\n"
"\n"
"    const int y2 = ((y + 2) < h) ? (y + 2) : (h - 2);\n"
"    const int32_t v2 = inBuf[getIdx(plane, x, y2)];\n"
"\n"
"    const int y4 = ((y + 4) < h) ? (y + 4) : (h - 2);\n"
"    const int32_t v4 = inBuf[getIdx(plane, x, y4)];\n"
"\n"
"    const int y6 = ((y + 6) < h) ? (y + 6) : (h - 2);\n"
"    const int32_t v6 = inBuf[getIdx(plane, x, y6)];\n"
"\n"
"    const int y8 = ((y + 8) < h) ? (y + 8) : (h - 2);\n"
"    const int32_t v8 = inBuf[getIdx(plane, x, y8)];\n"
"\n"
"    return v1 + fidelity_low(v_6, v_4, v_2, v0, v2, v4, v6, v8);\n"
"}\n"
"\n"
"void idwt_vert(int plane, int x, int y) {\n"
"    const int h = plane_sizes[plane].y;\n"
"\n"
"    const int32_t v0 = inBuf[getIdx(plane, x, y)];\n"
"    const int32_t v1 = fidelity_low_y(plane, x, y);\n"
"    const int32_t v_7 = (y - 8 > 0) ? fidelity_low_y(plane, x, y - 8) : v1;\n"
"    const int32_t v_5 = (y - 6 > 0) ? fidelity_low_y(plane, x, y - 6) : v1;\n"
"    const int32_t v_3 = (y - 4 > 0) ? fidelity_low_y(plane, x, y - 4) : v1;\n"
"    const int32_t v_1 = (y - 2 > 0) ? fidelity_low_y(plane, x, y - 2) : v1;\n"
"    const int32_t v3  = (y + 2 < h) ? fidelity_low_y(plane, x, y + 2) :\n"
"                                        fidelity_low_y(plane, x, h - 2);\n"
"    const int32_t v5  = (y + 4 < h) ? fidelity_low_y(plane, x, y + 4) :\n"
"                                        fidelity_low_y(plane, x, h - 2);\n"
"    const int32_t v7  = (y + 6 < h) ? fidelity_low_y(plane, x, y + 6) :\n"
"                                        fidelity_low_y(plane, x, h - 2);\n"
"    outBuf[getIdx(plane, x, y)] = v0 - fidelity_high(v_7, v_5, v_3, v_1, v1, v3, v5, v7);\n"
"    outBuf[getIdx(plane, x, y + 1)] = v1;\n"
"}\n"
"void main() {\n"
"    int off_y = int(gl_WorkGroupSize.y * gl_NumWorkGroups.y);\n"
"    int off_x = int(gl_WorkGroupSize.x * gl_NumWorkGroups.x);\n"
"    int pic_z = int(gl_GlobalInvocationID.z);\n"
"    uint h = int(plane_sizes[pic_z].y);\n"
"    uint w = int(plane_sizes[pic_z].x);\n"
"    int y = int(gl_GlobalInvocationID.y);\n"
"    for (; 2 * y < h; y += off_y) {\n"
"        int x = int(gl_GlobalInvocationID.x);\n"
"        for (; x < w; x += off_x) {\n"
"            idwt_vert(pic_z, x, 2 * y);\n"
"        }\n"
"    }\n"
"}\n"
;
