// Generated from libavcodec/vulkan/dirac/dirac_daub97_horiz.comp
const char *ff_source_dirac_daub97_horiz_comp =
"layout(push_constant, std430) uniform pushConstants {\n"
"    ivec2 plane_sizes[3];\n"
"    int plane_offs[3];\n"
"    int plane_strides[3];\n"
"    int dw[3];\n"
"    int wavelet_depth;\n"
"};\n"
"\n"
"int getIdx(int plane, int x, int y) {\n"
"  return plane_offs[plane] + plane_strides[plane] * y + x;\n"
"}\n"
"\n"
"int32_t daub97_low1(int32_t v1, int32_t v2, int32_t v3) {\n"
"  return  v2 - ((1817 * (v1 + v2) + 2048) >> 12);\n"
"}\n"
"\n"
"int32_t daub97_high1(int32_t v1, int32_t v2, int32_t v3) {\n"
"  return  v2 - ((113 * (v1 + v2) + 64) >> 7);\n"
"}\n"
"\n"
"int32_t daub97_low0(int32_t v1, int32_t v2, int32_t v3) {\n"
"  return  v2 - ((217 * (v1 + v2) + 2048) >> 12);\n"
"}\n"
"\n"
"int32_t daub97_high0(int32_t v1, int32_t v2, int32_t v3) {\n"
"  return  v2 - ((6947 * (v1 + v2) + 2048) >> 12);\n"
"}\n"
"\n"
"int32_t daub97_low_x0(int plane, int x, int y) {\n"
"    int w = plane_sizes[plane].x;\n"
"    int dw = plane_sizes[plane].x / 2;\n"
"\n"
"    int x0 = (x == 0) ? dw : x + dw;\n"
"    int32_t v0 = inBuf[getIdx(plane, x0, y)];\n"
"\n"
"    int32_t v1 = inBuf[getIdx(plane, x, y)];\n"
"\n"
"    int x2 = x + dw;\n"
"    int32_t v2 = inBuf[getIdx(plane, x0, y)];\n"
"\n"
"    return daub97_low1(v0, v1, v2);\n"
"}\n"
"\n"
"int32_t daub97_high_x0(int plane, int x, int y) {\n"
"    int w = plane_sizes[plane].x;\n"
"    int dw = plane_sizes[plane].x / 2;\n"
"\n"
"    int x0 = (x == dw - 1) ? (dw - 1) : (x - 1);\n"
"    int32_t v0 = daub97_low_x0(plane, x0, y);\n"
"\n"
"    int32_t v1 = inBuf[getIdx(plane, x + dw - 1, y)];\n"
"\n"
"    int32_t v2 = daub97_low_x0(plane, x, y);\n"
"\n"
"    return daub97_high1(v0, v1, v2);\n"
"}\n"
"\n"
"int32_t daub97_low_x1(int plane, int x, int y) {\n"
"    int w = plane_sizes[plane].x;\n"
"    int dw = plane_sizes[plane].x / 2;\n"
"\n"
"    int32_t v0 = daub97_high_x0(plane, x, y);\n"
"\n"
"    int32_t v1 = daub97_low_x0(plane, x, y);\n"
"\n"
"    int32_t v2 = daub97_high_x0(plane, x + 1, y);\n"
"\n"
"    return daub97_low0(v0, v1, v2);\n"
"}\n"
"\n"
"int32_t daub97_high_x1(int plane, int x, int y) {\n"
"    int w = plane_sizes[plane].x;\n"
"    int dw = plane_sizes[plane].x / 2;\n"
"\n"
"    int x0 = clamp(x - 1, 0, dw);\n"
"    int32_t v0 = daub97_low_x1(plane, x0, y);\n"
"\n"
"    int32_t v1 = daub97_high_x0(plane, x + 1, y);\n"
"\n"
"    int x2 = clamp(x, 0, dw);\n"
"    int32_t v2 = daub97_low_x1(plane, x2, y);\n"
"\n"
"    return daub97_high0(v0, v1, v2);\n"
"}\n"
"\n"
"void idwt_horiz(int plane, int x, int y) {\n"
"    int w = plane_sizes[plane].x;\n"
"    int dw = plane_sizes[plane].x / 2;\n"
"\n"
"    int32_t v0 = daub97_low_x1(plane, x, y);\n"
"    int32_t v1 = daub97_high_x1(plane, x, y);\n"
"\n"
"    outBuf[getIdx(plane, 2 * x, y)]     = ~((~v0) >> 1);\n"
"    outBuf[getIdx(plane, 2 * x + 1, y)] = ~((~v1) >> 1);\n"
"}\n"
"\n"
"void main() {\n"
"    int off_y = int(gl_WorkGroupSize.y * gl_NumWorkGroups.y);\n"
"    int off_x = int(gl_WorkGroupSize.x * gl_NumWorkGroups.x);\n"
"    int pic_z = int(gl_GlobalInvocationID.z);\n"
"    uint h = int(plane_sizes[pic_z].y);\n"
"    uint w = int(plane_sizes[pic_z].x);\n"
"    int y = int(gl_GlobalInvocationID.y);\n"
"    for (; y < h; y += off_y) {\n"
"        int x = int(gl_GlobalInvocationID.x);\n"
"        for (; 2 * x < w; x += off_x) {\n"
"            idwt_horiz(pic_z, x, y);\n"
"        }\n"
"    }\n"
"}\n"
;
