// Generated from libavcodec/vulkan/dirac/dirac_legall_vert.comp
const char *ff_source_dirac_legall_vert_comp =
"/*\n"
" * This file is part of FFmpeg.\n"
" *\n"
" * FFmpeg is free software; you can redistribute it and/or\n"
" * modify it under the terms of the GNU Lesser General Public\n"
" * License as published by the Free Software Foundation; either\n"
" * version 2.1 of the License, or (at your option) any later version.\n"
" *\n"
" * FFmpeg is distributed in the hope that it will be useful,\n"
" * but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n"
" * Lesser General Public License for more details.\n"
" *\n"
" * You should have received a copy of the GNU Lesser General Public\n"
" * License along with FFmpeg; if not, write to the Free Software\n"
" * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA\n"
" */\n"
"\n"
"layout(push_constant, std430) uniform pushConstants {\n"
"    ivec2 plane_sizes[3];\n"
"    int plane_offs[3];\n"
"    int plane_strides[3];\n"
"    int dw[3];\n"
"    int wavelet_depth;\n"
"};\n"
"\n"
"int getIdx(int plane, int x, int y) {\n"
"  return plane_offs[plane] + plane_strides[plane] * y + x;\n"
"}\n"
"\n"
"int32_t legall_low_y(int plane, int x, int y) {\n"
"    const int h = plane_sizes[plane].y;\n"
"    const int y_1 = ((y - 1) > 0) ? (y - 1) : 1;\n"
"    const int32_t val_1 = inBuf[getIdx(plane, x, y_1)];\n"
"    const int y0 = y;\n"
"    const int32_t val0 = inBuf[getIdx(plane, x, y0)];\n"
"    const int y1 = y + 1;\n"
"    const int32_t val1 = inBuf[getIdx(plane, x, y1)];\n"
"    return val0 - ((val1 + val_1 + 2) >> 2);\n"
"}\n"
"\n"
"\n"
"int32_t legall_high(int32_t v1, int32_t v2, int32_t v3) {\n"
"       return v1 + ((v2 + v3 + 1) >> 1);\n"
"}\n"
"\n"
"void idwt_vert(int plane, int x, int y) {\n"
"    const int h = plane_sizes[plane].y;\n"
"    const int32_t out0 = legall_low_y(plane, x, y);\n"
"    const int32_t yy = ((y + 2) < h) ? (y + 2) : (h - 2);\n"
"    const int32_t tmp1 = legall_low_y(plane, x, yy);\n"
"\n"
"    const int y1 = y + 1;\n"
"    const int32_t val1 = inBuf[getIdx(plane, x, y1)];\n"
"    const int32_t out1 = legall_high(val1, out0, tmp1);\n"
"\n"
"    outBuf[getIdx(plane, x, y)]     = out0;\n"
"    outBuf[getIdx(plane, x, y + 1)] = out1;\n"
"}\n"
"\n"
"void main() {\n"
"    int off_y = int(gl_WorkGroupSize.y * gl_NumWorkGroups.y);\n"
"    int off_x = int(gl_WorkGroupSize.x * gl_NumWorkGroups.x);\n"
"    int pic_z = int(gl_GlobalInvocationID.z);\n"
"    uint h = int(plane_sizes[pic_z].y);\n"
"    uint w = int(plane_sizes[pic_z].x);\n"
"    int y = int(gl_GlobalInvocationID.y);\n"
"\n"
"    for (; 2 * y < h; y += off_y) {\n"
"        int x = int(gl_GlobalInvocationID.x);\n"
"        for (; x < w; x += off_x) {\n"
"            idwt_vert(pic_z, x, 2 * y);\n"
"        }\n"
"    }\n"
"}\n"
;
