// Generated from libavcodec/vulkan/dirac/dirac_dd137_horiz.comp
const char *ff_source_dirac_dd137_horiz_comp =
"layout(push_constant, std430) uniform pushConstants {\n"
"    ivec2 plane_sizes[3];\n"
"    int plane_offs[3];\n"
"    int plane_strides[3];\n"
"    int dw[3];\n"
"    int wavelet_depth;\n"
"};\n"
"\n"
"int getIdx(int plane, int x, int y) {\n"
"  return plane_offs[plane] + plane_strides[plane] * y + x;\n"
"}\n"
"\n"
"int32_t dd137_low(int32_t v0, int32_t v1, int32_t v2, int32_t v3, int32_t v4) {\n"
"    return v2 - ((9 * v1 + 9 * v3 - v4 - v0 + 16) >> 5);\n"
"}\n"
"\n"
"int32_t dd97_high(int32_t v1, int32_t v2, int32_t v3, int32_t v4, int32_t v5) {\n"
"    return  v3 + ((9 * v4 + 9 * v2 - v5 - v1 + 8) >> 4);\n"
"}\n"
"\n"
"int32_t dd137_low_x(int plane, int x, int y) {\n"
"        const int w = plane_sizes[plane].x;\n"
"        const int dw = w / 2;\n"
"\n"
"        const int x0 = (x > 1) ? x : dw;\n"
"        const int32_t v0 = inBuf[getIdx(plane, x0, y)];\n"
"\n"
"        const int x1 = (x > 1) ? (x + dw - 2) : dw;\n"
"        const int32_t v1 = inBuf[getIdx(plane, x1, y)];\n"
"\n"
"        const int x2 = x;\n"
"        const int32_t v2 = inBuf[getIdx(plane, x2, y)];\n"
"\n"
"        const int x3 = x + dw;\n"
"        const int32_t v3 = inBuf[getIdx(plane, x3, y)];\n"
"\n"
"        const int x4 = (x != dw - 1) ? (x + dw + 1) : (dw - 1);\n"
"        const int32_t v4 = inBuf[getIdx(plane, x4, y)];\n"
"\n"
"        return dd137_low(v0, v1, v2, v3, v4);\n"
"}\n"
"\n"
"void idwt_horiz(int plane, int x, int y) {\n"
"    const int w = plane_sizes[plane].x;\n"
"    const int dw = w / 2 - 1;\n"
"\n"
"    const int32_t out0 = dd137_low_x(plane, x, y);\n"
"\n"
"    const int32_t out_1 = ((x - 1) > 0) ? dd137_low_x(plane, x - 1, y) : out0;\n"
"    const int32_t val3 = inBuf[getIdx(plane, x + dw + 1, y)];\n"
"    const int32_t out1 = ((x + 1) <= dw) ? dd137_low_x(plane, x + 1, y) :\n"
"                                            dd137_low_x(plane, dw, y);\n"
"    const int32_t out2 = ((x + 2) <= dw) ? dd137_low_x(plane, x + 2, y) :\n"
"                                            dd137_low_x(plane, dw, y);\n"
"    const int32_t res  = dd97_high(out_1, out0, val3, out1, out2);\n"
"\n"
"    outBuf[getIdx(plane, 2 * x, y)]     = (out0 + 1) >> 1;\n"
"    outBuf[getIdx(plane, 2 * x + 1, y)] = (res + 1) >> 1;\n"
"}\n"
"\n"
"void main() {\n"
"    int off_y = int(gl_WorkGroupSize.y * gl_NumWorkGroups.y);\n"
"    int off_x = int(gl_WorkGroupSize.x * gl_NumWorkGroups.x);\n"
"    int pic_z = int(gl_GlobalInvocationID.z);\n"
"    uint h = int(plane_sizes[pic_z].y);\n"
"    uint w = int(plane_sizes[pic_z].x);\n"
"    int y = int(gl_GlobalInvocationID.y);\n"
"    for (; y < h; y += off_y) {\n"
"        int x = int(gl_GlobalInvocationID.x);\n"
"        for (; 2 * x < w; x += off_x) {\n"
"            idwt_horiz(pic_z, x, y);\n"
"        }\n"
"    }\n"
"}\n"
;
