// Generated from libavcodec/vulkan/dirac/dirac_dequant.comp
const char *ff_source_dirac_dequant_comp =
"/*\n"
" * This file is part of FFmpeg.\n"
" *\n"
" * FFmpeg is free software; you can redistribute it and/or\n"
" * modify it under the terms of the GNU Lesser General Public\n"
" * License as published by the Free Software Foundation; either\n"
" * version 2.1 of the License, or (at your option) any later version.\n"
" *\n"
" * FFmpeg is distributed in the hope that it will be useful,\n"
" * but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n"
" * Lesser General Public License for more details.\n"
" *\n"
" * You should have received a copy of the GNU Lesser General Public\n"
" * License along with FFmpeg; if not, write to the Free Software\n"
" * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA\n"
" */\n"
"\n"
"layout(push_constant, std430) uniform pushConstants {\n"
"    ivec2 plane_sizes[3];\n"
"    int plane_offs[3];\n"
"    int plane_strides[3];\n"
"    int dw[3];\n"
"    int wavelet_depth;\n"
"};\n"
"\n"
"int32_t dequant_imm(int32_t val, int qf, int qs) {\n"
"    return sign(val) * ((abs(val) * qf + qs) >> 2);\n"
"}\n"
"\n"
"void proc_slice(int slice_idx) {\n"
"    const int plane = int(gl_GlobalInvocationID.y);\n"
"\n"
"    const int base_idx = slice_idx * DWT_LEVELS * 8;\n"
"    const int base_slice_idx = slice_idx * DWT_LEVELS * 3 + plane * DWT_LEVELS;\n"
"\n"
"\n"
"    Slice s = slices[base_slice_idx];\n"
"    int len = s.len;\n"
"    int offs = s.offs;\n"
"    int n = 0;\n"
"\n"
"    for(int level = 0; level < wavelet_depth; level++) {\n"
"        s = slices[base_slice_idx + level];\n"
"\n"
"        for(int orient = int(bool(level)); orient < 4; orient++) {\n"
"            int32_t qf = quantMatrix[base_idx + level * 8 + orient];\n"
"            int32_t qs = quantMatrix[base_idx + level * 8 + orient + 4];\n"
"\n"
"            const int subband_idx = plane * DWT_LEVELS * 4\n"
"                                        + 4 * level + orient;\n"
"\n"
"            const SubbandOffset sub_off = subband_offs[subband_idx];\n"
"            int img_idx = plane_offs[plane] + sub_off.base_off\n"
"                            + s.top * sub_off.stride + s.left;\n"
"            LUTState lut = dirac_golomb_lut[inBuffer[offs]], prev_lut;\n"
"\n"
"            int x = 0;\n"
"            int32_t val = 0;\n"
"            for(int y = 0; y < s.tot_v; y++) {\n"
"                int32_t buf[8];\n"
"                int cur_idx = 0;\n"
"                while (x < s.tot_h) {\n"
"                    if (n <= len) {\n"
"                        val  = (val << lut.val0_bits) | lut.val0;\n"
"                        buf[0] = dequant_imm((val - 1) * lut.sign, qf, qs);\n"
"                        buf[1] = dequant_imm(lut.val1, qf, qs);\n"
"                        buf[2] = dequant_imm(lut.val2, qf, qs);\n"
"                        buf[3] = dequant_imm(lut.val3, qf, qs);\n"
"                        buf[4] = dequant_imm(lut.val4, qf, qs);\n"
"                        buf[5] = 0;\n"
"                        buf[6] = 0;\n"
"                        buf[7] = 0;\n"
"                        val = lut.num == 0 ? val : lut.val;\n"
"                    }\n"
"                    int min_it = min(s.tot_h - x, lut.num);\n"
"                    for (cur_idx = 0; cur_idx < min_it; cur_idx++) {\n"
"                        if (n > len) {\n"
"                            outBuf0[img_idx + x] = 0;\n"
"                            outBuf1[img_idx + x] = 0;\n"
"                        } else {\n"
"                            outBuf0[img_idx + x] = buf[cur_idx];\n"
"                            outBuf1[img_idx + x] = buf[cur_idx];\n"
"                        }\n"
"                        x++;\n"
"                        n++;\n"
"                    }\n"
"\n"
"                    offs++;\n"
"                    prev_lut = lut;\n"
"                    lut = dirac_golomb_lut[lut.state + inBuffer[offs]];\n"
"                }\n"
"                img_idx += sub_off.stride;\n"
"                x = 0;\n"
"                for (;cur_idx < prev_lut.num && y != s.tot_v - 1; cur_idx++) {\n"
"                    if (n > len) {\n"
"                        outBuf0[img_idx + x] = 0;\n"
"                        outBuf1[img_idx + x] = 0;\n"
"                    } else {\n"
"                        outBuf0[img_idx + x] = buf[cur_idx];\n"
"                        outBuf1[img_idx + x] = buf[cur_idx];\n"
"                    }\n"
"                    x++;\n"
"                    n++;\n"
"                }\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"void main() {\n"
"    int idx = int(gl_GlobalInvocationID.x);\n"
"    proc_slice(idx);\n"
"}\n"
;
