// Generated from libavcodec/vulkan/dirac/dirac_cpy_to_image_12bit.comp
const char *ff_source_dirac_cpy_to_image_12bit_comp =
"layout(push_constant, std430) uniform pushConstants {\n"
"    ivec2 plane_sizes[3];\n"
"    int plane_offs[3];\n"
"    int plane_strides[3];\n"
"    int dw[3];\n"
"    int wavelet_depth;\n"
"};\n"
"\n"
"\n"
"void main() {\n"
"    int x = int(gl_GlobalInvocationID.x);\n"
"    int y = int(gl_GlobalInvocationID.y);\n"
"    int plane = int(gl_GlobalInvocationID.z);\n"
"    if (!IS_WITHIN(ivec2(x, y), imageSize(out_img[plane]))) {\n"
"        return;\n"
"    }\n"
"    int idx = plane_offs[plane] + y * plane_strides[plane] + x;\n"
"    int32_t ival = inBuf[idx] + 2048;\n"
"    float val = float(clamp(ival, 0, 4096)) / 65536.0;\n"
"    imageStore(out_img[plane], ivec2(x, y), vec4(val));\n"
"    memoryBarrier();\n"
"}\n"
;
