// Generated from libavcodec/vulkan/dirac/dirac_cpy_to_image_8bit.comp
const char *ff_source_dirac_cpy_to_image_8bit_comp =
"/*\n"
" * This file is part of FFmpeg.\n"
" *\n"
" * FFmpeg is free software; you can redistribute it and/or\n"
" * modify it under the terms of the GNU Lesser General Public\n"
" * License as published by the Free Software Foundation; either\n"
" * version 2.1 of the License, or (at your option) any later version.\n"
" *\n"
" * FFmpeg is distributed in the hope that it will be useful,\n"
" * but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n"
" * Lesser General Public License for more details.\n"
" *\n"
" * You should have received a copy of the GNU Lesser General Public\n"
" * License along with FFmpeg; if not, write to the Free Software\n"
" * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA\n"
" */\n"
"\n"
"layout(push_constant, std430) uniform pushConstants {\n"
"    ivec2 plane_sizes[3];\n"
"    int plane_offs[3];\n"
"    int plane_strides[3];\n"
"    int dw[3];\n"
"    int wavelet_depth;\n"
"};\n"
"\n"
"\n"
"void main() {\n"
"    int x = int(gl_GlobalInvocationID.x);\n"
"    int y = int(gl_GlobalInvocationID.y);\n"
"    int plane = int(gl_GlobalInvocationID.z);\n"
"    if (!IS_WITHIN(ivec2(x, y), imageSize(out_img[plane]))) {\n"
"        return;\n"
"    }\n"
"    int idx = plane_offs[plane] + y * plane_strides[plane] + x;\n"
"    int32_t ival = inBuf[idx] + 128;\n"
"    float val = float(clamp(ival, 0, 256)) / 255.0;\n"
"    imageStore(out_img[plane], ivec2(x, y), vec4(val));\n"
"    memoryBarrier();\n"
"}\n"
;
