// Generated from libavcodec/vulkan/dirac/dirac_dd137_vert.comp
const char *ff_source_dirac_dd137_vert_comp =
"layout(push_constant, std430) uniform pushConstants {\n"
"    ivec2 plane_sizes[3];\n"
"    int plane_offs[3];\n"
"    int plane_strides[3];\n"
"    int dw[3];\n"
"    int wavelet_depth;\n"
"};\n"
"\n"
"int getIdx(int plane, int x, int y) {\n"
"  return plane_offs[plane] + plane_strides[plane] * y + x;\n"
"}\n"
"\n"
"int32_t dd137_low(int32_t v0, int32_t v1, int32_t v2, int32_t v3, int32_t v4) {\n"
"    return v2 - ((9 * v1 + 9 * v3 - v4 - v0 + 16) >> 5);\n"
"}\n"
"\n"
"int32_t dd97_high(int32_t v1, int32_t v2, int32_t v3, int32_t v4, int32_t v5) {\n"
"    return  v3 + ((9 * v4 + 9 * v2 - v5 - v1 + 8) >> 4);\n"
"}\n"
"\n"
"int32_t dd137_low_y(int plane, int x, int y) {\n"
"    const int h = plane_sizes[plane].y;\n"
"\n"
"    const int y0 = (x > 3) ? (y - 3) : 1;\n"
"    const int32_t v0 = inBuf[getIdx(plane, x, y0)];\n"
"\n"
"    const int y1 = (y > 1) ? (y - 1) : 1;\n"
"    const int32_t v1 = inBuf[getIdx(plane, x, y1)];\n"
"\n"
"    const int y2 = y;\n"
"    const int32_t v2 = inBuf[getIdx(plane, x, y2)];\n"
"\n"
"    const int y3 = y + 1;\n"
"    const int32_t v3 = inBuf[getIdx(plane, x, y3)];\n"
"\n"
"    const int y4 = (y + 3 < h) ? (y + 3) : (h - 1);\n"
"    const int32_t v4 = inBuf[getIdx(plane, x, y4)];\n"
"\n"
"    return dd137_low(v0, v1, v2, v3, v4);\n"
"}\n"
"\n"
"void idwt_vert(int plane, int x, int y) {\n"
"    const int h = plane_sizes[plane].y;\n"
"\n"
"    const int32_t out0 = dd137_low_y(plane, x, y);\n"
"    const int32_t out_2 = (y - 2 > 0) ? dd137_low_y(plane, x, y - 2) :\n"
"                                        dd137_low_y(plane, x, 0);\n"
"    const int32_t out2 = (y + 2 < h) ? dd137_low_y(plane, x, y + 2) :\n"
"                                        dd137_low_y(plane, x, h - 2);\n"
"    const int32_t out4 = (y + 4 < h) ? dd137_low_y(plane, x, y + 4) :\n"
"                                        dd137_low_y(plane, x, h - 2);\n"
"    const int32_t val1 = inBuf[getIdx(plane, x, y + 1)];\n"
"\n"
"    outBuf[getIdx(plane, x, y)]     = out0;\n"
"    outBuf[getIdx(plane, x, y + 1)] = dd97_high(out_2, out0, val1, out2, out4);\n"
"}\n"
"\n"
"\n"
"\n"
"void main() {\n"
"    int off_y = int(gl_WorkGroupSize.y * gl_NumWorkGroups.y);\n"
"    int off_x = int(gl_WorkGroupSize.x * gl_NumWorkGroups.x);\n"
"    int pic_z = int(gl_GlobalInvocationID.z);\n"
"    uint h = int(plane_sizes[pic_z].y);\n"
"    uint w = int(plane_sizes[pic_z].x);\n"
"    int y = int(gl_GlobalInvocationID.y);\n"
"    for (; 2 * y < h; y += off_y) {\n"
"        int x = int(gl_GlobalInvocationID.x);\n"
"        for (; x < w; x += off_x) {\n"
"            idwt_vert(pic_z, x, 2 * y);\n"
"        }\n"
"    }\n"
"}\n"
;
