// Generated from libavcodec/vulkan/dirac/dirac_dequant.comp
const char *ff_source_dirac_dequant_comp =
"/*\n"
" * This file is part of FFmpeg.\n"
" *\n"
" * FFmpeg is free software; you can redistribute it and/or\n"
" * modify it under the terms of the GNU Lesser General Public\n"
" * License as published by the Free Software Foundation; either\n"
" * version 2.1 of the License, or (at your option) any later version.\n"
" *\n"
" * FFmpeg is distributed in the hope that it will be useful,\n"
" * but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n"
" * Lesser General Public License for more details.\n"
" *\n"
" * You should have received a copy of the GNU Lesser General Public\n"
" * License along with FFmpeg; if not, write to the Free Software\n"
" * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA\n"
" */\n"
"\n"
"layout(push_constant, std430) uniform pushConstants {\n"
"    ivec2 plane_sizes[3];\n"
"    int plane_offs[3];\n"
"    int plane_strides[3];\n"
"    int dw[3];\n"
"    int wavelet_depth;\n"
"};\n"
"\n"
"void dequant(int outIdx, int idx, int qf, int qs) {\n"
"    int32_t val = inBuffer[idx];\n"
"    val = sign(val) * ((abs(val) * qf + qs) >> 2);\n"
"    outBuf0[outIdx] = outBuf1[outIdx] = val;\n"
"}\n"
"\n"
"const uint16_t STATE_START  = uint16_t(0);\n"
"const uint16_t STATE_FOLLOW = uint16_t(256);\n"
"const uint16_t STATE_DATA   = uint16_t(512);\n"
"const uint16_t STATE_SIGN   = uint16_t(768);\n"
"\n"
"int32_t dequant_imm(int val, int qf, int qs) {\n"
"    return sign(val) * ((abs(val) * qf + qs) >> 2);\n"
"}\n"
"\n"
"void decode_and_dequant(int offs, int bytes, int dst, int qf, int qs)\n"
"{\n"
"    int next_val = inBuffer[offs];\n"
"    int idx = 1;\n"
"    int cur_idx = 0;\n"
"    int num_all = 0;\n"
"    int32_t val = 0;\n"
"    LUTState lut = dirac_golomb_lut[inBuffer[offs]];\n"
"\n"
"    for (int i = 1; i < bytes; i++) {\n"
"        val  = (val << lut.val0_bits) | lut.val0;\n"
"        int real_dst = dst + cur_idx;\n"
"        outBuf0[real_dst] = outBuf1[real_dst] = dequant_imm((val - 1) * lut.sign, qf, qs);\n"
"        outBuf0[real_dst + 1] = outBuf1[real_dst + 1] = dequant_imm(lut.val1, qf, qs);\n"
"        outBuf0[real_dst + 2] = outBuf1[real_dst + 2] = dequant_imm(lut.val2, qf, qs);\n"
"        outBuf0[real_dst + 3] = outBuf1[real_dst + 3] = dequant_imm(lut.val3, qf, qs);\n"
"        outBuf0[real_dst + 4] = outBuf1[real_dst + 4] = dequant_imm(lut.val4, qf, qs);\n"
"        outBuf0[real_dst + 5] = outBuf1[real_dst + 5] = 0;\n"
"        outBuf0[real_dst + 6] = outBuf1[real_dst + 6] = 0;\n"
"        outBuf0[real_dst + 7] = outBuf1[real_dst + 7] = 0;\n"
"        if (lut.num != 0) {\n"
"            val = lut.val;\n"
"        }\n"
"        cur_idx += lut.num;\n"
"        if (cur_idx >= bytes){\n"
"            return;\n"
"        }\n"
"        idx++;\n"
"        next_val = int(inBuffer[offs + idx]);\n"
"        lut = dirac_golomb_lut[lut.state + next_val];\n"
"    }\n"
"}\n"
"\n"
"void proc_slice(int slice_idx) {\n"
"    const int plane = int(gl_GlobalInvocationID.y);\n"
"\n"
"    const int base_idx = slice_idx * DWT_LEVELS * 8;\n"
"    const int base_slice_idx = slice_idx * DWT_LEVELS * 3 + plane * DWT_LEVELS;\n"
"\n"
"\n"
"    Slice s = slices[base_slice_idx];\n"
"    int offs = s.offs;\n"
"\n"
"    for(int level = 0; level < wavelet_depth; level++) {\n"
"        Slice s = slices[base_slice_idx + level];\n"
"\n"
"\n"
"        for(int orient = int(bool(level)); orient < 4; orient++) {\n"
"            int32_t qf = quantMatrix[base_idx + level * 8 + orient];\n"
"            int32_t qs = quantMatrix[base_idx + level * 8 + orient + 4];\n"
"\n"
"            const int subband_idx = plane * DWT_LEVELS * 4\n"
"                                        + 4 * level + orient;\n"
"\n"
"            const SubbandOffset sub_off = subband_offs[subband_idx];\n"
"            int img_idx = plane_offs[plane] + sub_off.base_off\n"
"                            + s.top * sub_off.stride + s.left;\n"
"            LUTState lut = dirac_golomb_lut[inBuffer[offs]];\n"
"            offs++;\n"
"\n"
"            int x = 0;\n"
"            int32_t val = 0;\n"
"            for(int y = 0; y < s.tot_v; y++) {\n"
"                int32_t buf[8];\n"
"                int cur_idx = 0;\n"
"                while (x < s.tot_h) {\n"
"                    val  = (val << lut.val0_bits) | lut.val0;\n"
"                    buf[0] = dequant_imm((val - 1) * lut.sign, qf, qs);\n"
"                    buf[1] = dequant_imm(lut.val1, qf, qs);\n"
"                    buf[2] = dequant_imm(lut.val2, qf, qs);\n"
"                    buf[3] = dequant_imm(lut.val3, qf, qs);\n"
"                    buf[4] = dequant_imm(lut.val4, qf, qs);\n"
"                    buf[5] = 0;\n"
"                    buf[6] = 0;\n"
"                    buf[7] = 0;\n"
"                    val = lut.num == 0 ? val : lut.val;\n"
"                    for (cur_idx = 0; x + cur_idx < s.tot_h && cur_idx < lut.num; cur_idx++) {\n"
"                        outBuf0[img_idx + x + cur_idx] = buf[cur_idx];\n"
"                        outBuf1[img_idx + x + cur_idx] = buf[cur_idx];\n"
"                    }\n"
"\n"
"                    x += lut.num;\n"
"                    debugPrintfEXT(\"Val0: %i\\n\", buf[0]);\n"
"\n"
"                    lut = dirac_golomb_lut[lut.state + inBuffer[offs]];\n"
"                    offs++;\n"
"                }\n"
"                img_idx += sub_off.stride;\n"
"                x = cur_idx;\n"
"                // for (;x <= lut.num; x++) {\n"
"                //     outBuf0[img_idx + x] = buf[x];\n"
"                //     outBuf1[img_idx + x] = buf[x];\n"
"                // }\n"
"                // for(int x = 0; x < s.tot_h;) {\n"
"                //     offs++;\n"
"                //     val = (val << lut.val0_bits) | lut.val0;\n"
"                //     debugPrintfEXT(\"Val0 bits: %i\\n\", int(lut.val0_bits));\n"
"                //     x += lut.num;\n"
"                //     lut = dirac_golomb_lut[offs + lut.state];\n"
"                //     offs++;\n"
"                //     // outBuf0[img_x + x] = outBuf1[img_x + x]\n"
"                // }\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"void main() {\n"
"    int idx = int(gl_GlobalInvocationID.x);\n"
"    proc_slice(idx);\n"
"}\n"
;
