// Generated from libavcodec/vulkan/dirac/dirac_dd97_horiz.comp
const char *ff_source_dirac_dd97_horiz_comp =
"/*\n"
" * This file is part of FFmpeg.\n"
" *\n"
" * FFmpeg is free software; you can redistribute it and/or\n"
" * modify it under the terms of the GNU Lesser General Public\n"
" * License as published by the Free Software Foundation; either\n"
" * version 2.1 of the License, or (at your option) any later version.\n"
" *\n"
" * FFmpeg is distributed in the hope that it will be useful,\n"
" * but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n"
" * Lesser General Public License for more details.\n"
" *\n"
" * You should have received a copy of the GNU Lesser General Public\n"
" * License along with FFmpeg; if not, write to the Free Software\n"
" * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA\n"
" */\n"
"\n"
"layout(push_constant, std430) uniform pushConstants {\n"
"    ivec2 plane_sizes[3];\n"
"    int plane_offs[3];\n"
"    int plane_strides[3];\n"
"    int dw[3];\n"
"    int wavelet_depth;\n"
"};\n"
"\n"
"int getIdx(int plane, int x, int y) {\n"
"  return plane_offs[plane] + plane_strides[plane] * y + x;\n"
"}\n"
"\n"
"int32_t legall_high(int32_t v1, int32_t v2, int32_t v3) {\n"
"       return v1 + ((v2 + v3 + 1) >> 1);\n"
"}\n"
"\n"
"int32_t legall_low_x(int plane, int x, int y) {\n"
"    const int w = plane_sizes[plane].x;\n"
"    const int dw = w / 2;\n"
"\n"
"    const int x_1 = (x > 0) ? x : 0;\n"
"    const int32_t val_1 = inBuf[getIdx(plane, x_1, y)];\n"
"    const int x1 = (x > 0) ? (x + dw) : dw;\n"
"\n"
"    const int32_t val1 = inBuf[getIdx(plane, x1, y)];\n"
"    const int x0 = (x > 0) ? (x + dw - 1) : dw;\n"
"    const int32_t val0 = inBuf[getIdx(plane, x0, y)];\n"
"\n"
"    return val_1 - ((val0 + val1 + 2) >> 2);\n"
"}\n"
"\n"
"int32_t dd97_high(int32_t v1, int32_t v2, int32_t v3, int32_t v4, int32_t v5) {\n"
"    return  v3 + ((9 * v4 + 9 * v2 - v5 - v1 + 8) >> 4);\n"
"}\n"
"\n"
"void idwt_horiz(int plane, int x, int y) {\n"
"    const int w = plane_sizes[plane].x;\n"
"    const int dw = w / 2 - 1;\n"
"\n"
"    const int32_t out0 = legall_low_x(plane, x, y);\n"
"\n"
"    const int32_t out_1 = ((x - 1) > 0) ? legall_low_x(plane, x - 1, y) : out0;\n"
"    const int32_t val3 = inBuf[getIdx(plane, x + dw + 1, y)];\n"
"    const int32_t out1 = ((x + 1) <= dw) ? legall_low_x(plane, x + 1, y) :\n"
"                                            legall_low_x(plane, dw, y);\n"
"    const int32_t out2 = ((x + 2) <= dw) ? legall_low_x(plane, x + 2, y) :\n"
"                                            legall_low_x(plane, dw, y);\n"
"    const int32_t res  = dd97_high(out_1, out0, val3, out1, out2);\n"
"\n"
"    outBuf[getIdx(plane, 2 * x, y)]     = (out0 + 1) >> 1;\n"
"    outBuf[getIdx(plane, 2 * x + 1, y)] = (res + 1) >> 1;\n"
"}\n"
"\n"
"void main() {\n"
"    int off_y = int(gl_WorkGroupSize.y * gl_NumWorkGroups.y);\n"
"    int off_x = int(gl_WorkGroupSize.x * gl_NumWorkGroups.x);\n"
"    int pic_z = int(gl_GlobalInvocationID.z);\n"
"    uint h = int(plane_sizes[pic_z].y);\n"
"    uint w = int(plane_sizes[pic_z].x);\n"
"    int y = int(gl_GlobalInvocationID.y);\n"
"\n"
"    for (; y < h; y += off_y) {\n"
"        int x = int(gl_GlobalInvocationID.x);\n"
"        for (; 2 * x < w; x += off_x) {\n"
"            idwt_horiz(pic_z, x, y);\n"
"        }\n"
"    }\n"
"}\n"
;
